version: '3'
services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      ACCEPT_EULA: "1"
      SA_PASSWORD: "reallyStrongPwd123"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"